### ISSUE TITLE
accidentally sent money to default address

### ISSUE THREAD

**Issue by ste123452** [AliasIO/BitcoinQRCode.org#10]
hi, I tried sending some bitcoins to my wallet but there was an issue because I was using a picture of the qr code which I took with my phone. I tried to take another picture but didn't realise the address had gone back to the default one and so I sent the money to your default address and I'm wondering if you could forward it on to my wallet.

**Comment by ste123452** [comment]
Great help, thank you very much

**Comment by samuelripp09** [comment]
Did the exact same thing, sent him an email about it. Hope he responds :/ Did he refund your coin?

**Comment by samuelripp09** [comment]
I feel stupid as hell :/

**Comment by ste123452** [comment]
Yeah he did, it takes a while for him to respond but he should sort it out

**Comment by samuelripp09** [comment]
How long did it take? Haven't heard back from him since the first time I emailed him and the tent is due on the fifth :/

**Comment by ste123452** [comment]
It took him 3 days to sort it out for me

**Comment by samuelripp09** [comment]
Been that long for me, hopefully it happens soon. Thanks for updating me.

**Comment by ste123452** [comment]
No worries pal, good luck
