### ISSUE TITLE
Accidentally sent BTC to your address!

### ISSUE THREAD

**Issue by mrincredible2017** [AliasIO/BitcoinQRCode.org#5]
Acidentally sent coins to your bitcoin address! Was trying to use your Bitcoin QR code generator and it didn't update to the correct address, for some reason your site has a default address in there which is the same as your donation address. So my coins have been sent to your donation address. Please send them back to me or to my recipient. I have emailed you already, but no reply so far.

**Comment by mrincredible2017** [comment]
Personally I don't think there should be any default btc address then it would avoid this situation.

**Comment by mrincredible2017** [comment]
Please answer asap.

**Comment by AliasIO** [comment]
Please send me an email (elbert at alias.io) with the transaction ID and return address.
